-- MySQL Script generated by MySQL Workbench
-- 05/30/15 12:47:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projet_Lo07
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projet_Lo07` ;

-- -----------------------------------------------------
-- Schema projet_Lo07
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_Lo07` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `projet_Lo07` ;

-- -----------------------------------------------------
-- Table `projet_Lo07`.`membres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_Lo07`.`membres` ;

CREATE TABLE IF NOT EXISTS `projet_Lo07`.`membres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `annee_naissance` YEAR NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_Lo07`.`trajets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_Lo07`.`trajets` ;

CREATE TABLE IF NOT EXISTS `projet_Lo07`.`trajets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ville_depart_id` INT NOT NULL,
  `ville_arrivee_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `heure` VARCHAR(2) NOT NULL,
  `nbr_places_disponibles` INT NOT NULL,
  `nbr_places_reservees` INT NOT NULL,
  `prix` INT NOT NULL,
  `membres_id` INT NOT NULL,
  PRIMARY KEY (`id`, `membres_id`),
  CONSTRAINT `fk_trajets_membres1`
    FOREIGN KEY (`membres_id`)
    REFERENCES `projet_Lo07`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_trajets_membres1_idx` ON `projet_Lo07`.`trajets` (`membres_id` ASC);


-- -----------------------------------------------------
-- Table `projet_Lo07`.`membres_has_trajets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_Lo07`.`membres_has_trajets` ;

CREATE TABLE IF NOT EXISTS `projet_Lo07`.`membres_has_trajets` (
  `membres_id` INT NOT NULL,
  `trajets_id` INT NOT NULL,
  PRIMARY KEY (`membres_id`, `trajets_id`),
  CONSTRAINT `fk_membres_has_trajets_membres`
    FOREIGN KEY (`membres_id`)
    REFERENCES `projet_Lo07`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membres_has_trajets_trajets1`
    FOREIGN KEY (`trajets_id`)
    REFERENCES `projet_Lo07`.`trajets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_membres_has_trajets_trajets1_idx` ON `projet_Lo07`.`membres_has_trajets` (`trajets_id` ASC);

CREATE INDEX `fk_membres_has_trajets_membres_idx` ON `projet_Lo07`.`membres_has_trajets` (`membres_id` ASC);


-- -----------------------------------------------------
-- Table `projet_Lo07`.`commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_Lo07`.`commentaires` ;

CREATE TABLE IF NOT EXISTS `projet_Lo07`.`commentaires` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `avis` LONGTEXT NOT NULL,
  `note` INT(5) NOT NULL,
  `membres_id` INT NOT NULL,
  PRIMARY KEY (`id`, `membres_id`),
  CONSTRAINT `fk_commentaires_membres1`
    FOREIGN KEY (`membres_id`)
    REFERENCES `projet_Lo07`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_commentaires_membres1_idx` ON `projet_Lo07`.`commentaires` (`membres_id` ASC);


-- -----------------------------------------------------
-- Table `projet_Lo07`.`vehicules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_Lo07`.`vehicules` ;

CREATE TABLE IF NOT EXISTS `projet_Lo07`.`vehicules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marque` VARCHAR(45) NOT NULL,
  `couleur` VARCHAR(45) NOT NULL,
  `modele` VARCHAR(45) NOT NULL,
  `annee_mise_en_circulation` YEAR NOT NULL,
  `membres_id` INT NOT NULL,
  PRIMARY KEY (`id`, `membres_id`),
  CONSTRAINT `fk_vehicules_membres1`
    FOREIGN KEY (`membres_id`)
    REFERENCES `projet_Lo07`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vehicules_membres1_idx` ON `projet_Lo07`.`vehicules` (`membres_id` ASC);


-- -----------------------------------------------------
-- Table `projet_Lo07`.`villes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_Lo07`.`villes` ;

CREATE TABLE IF NOT EXISTS `projet_Lo07`.`villes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_Lo07`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_Lo07`.`messages` ;

CREATE TABLE IF NOT EXISTS `projet_Lo07`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` LONGTEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `membres_id` INT NOT NULL,
  PRIMARY KEY (`id`, `membres_id`),
  CONSTRAINT `fk_messages_membres1`
    FOREIGN KEY (`membres_id`)
    REFERENCES `projet_Lo07`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_messages_membres1_idx` ON `projet_Lo07`.`messages` (`membres_id` ASC);


-- -----------------------------------------------------
-- Table `projet_Lo07`.`membres_has_commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_Lo07`.`membres_has_commentaires` ;

CREATE TABLE IF NOT EXISTS `projet_Lo07`.`membres_has_commentaires` (
  `membres_id` INT NOT NULL,
  `commentaires_id` INT NOT NULL,
  PRIMARY KEY (`membres_id`, `commentaires_id`),
  CONSTRAINT `fk_membres_has_commentaires_membres1`
    FOREIGN KEY (`membres_id`)
    REFERENCES `projet_Lo07`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membres_has_commentaires_commentaires1`
    FOREIGN KEY (`commentaires_id`)
    REFERENCES `projet_Lo07`.`commentaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_membres_has_commentaires_commentaires1_idx` ON `projet_Lo07`.`membres_has_commentaires` (`commentaires_id` ASC);

CREATE INDEX `fk_membres_has_commentaires_membres1_idx` ON `projet_Lo07`.`membres_has_commentaires` (`membres_id` ASC);


-- -----------------------------------------------------
-- Table `projet_Lo07`.`membres_has_messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_Lo07`.`membres_has_messages` ;

CREATE TABLE IF NOT EXISTS `projet_Lo07`.`membres_has_messages` (
  `membres_id` INT NOT NULL,
  `messages_id` INT NOT NULL,
  PRIMARY KEY (`membres_id`, `messages_id`),
  CONSTRAINT `fk_membres_has_messages_membres1`
    FOREIGN KEY (`membres_id`)
    REFERENCES `projet_Lo07`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membres_has_messages_messages1`
    FOREIGN KEY (`messages_id`)
    REFERENCES `projet_Lo07`.`messages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_membres_has_messages_messages1_idx` ON `projet_Lo07`.`membres_has_messages` (`messages_id` ASC);

CREATE INDEX `fk_membres_has_messages_membres1_idx` ON `projet_Lo07`.`membres_has_messages` (`membres_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
